server:
  port: 8080
spring:
  application:
    name: "OnlineLearningApp"
  datasource:
    url: jdbc:mysql://localhost:3306/onlinelearningapp
    username: root
    password: Karna@2019#
    driver-class-name: com.mysql.cj.jdbc.Driver # Correct driver for MySQL 8+

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect # For MySQL 8+
    hibernate:
      ddl-auto: update # Good for development; consider 'validate' or 'none' for production
    show-sql: true # Shows SQL queries in the console (useful for debugging)

  servlet:
    context-path: /api # Your application's base path for all endpoints


