services:
   db:
    image: mysql:8
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: online_learning
    healthcheck:
      test: ["CMD","mysqladmin", "ping","-h","localhost"]
      interval: 5s
      timeout: 180s
      retries: 5
      start_period: 30s
    ports:
      - "3305:3306"
    networks:
      - backend
   app:
    image: "rkolluri/onlinelearningapp:s1"
    container_name: onlinelearningapp
    ports:
     - 8080:8080
    depends_on:
      db:
       condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/online_learning
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - backend
   

networks:
  backend:
    driver: bridge
