name: setup Java and publish artifact


on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  build_test:

    runs-on: ubuntu_latest

    steps:
    - uses: actions/checkout@v4
    - name: setup up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'corretto' 
        java-version: '17'
        cache: maven
    - name: build with maven
      run: mvn -B package --file pom.xml
